from __future__ import annotations

from pathlib import Path

import numpy as np

from .frames import read_frame_manifest
from .vggt import import_predictions_npz


def _to_numpy_array(value):
    if hasattr(value, "detach"):
        return value.detach().cpu().numpy()
    if isinstance(value, dict):
        return {key: _to_numpy_array(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_numpy_array(item) for item in value]
    return value


def run_installed_vggt(
    frame_manifest_path: Path,
    predictions_output: Path,
    bundle_output: Path,
    source_url_or_repo: str = "https://github.com/facebookresearch/vggt",
    source_commit_or_version: str | None = None,
    allow_cpu: bool = False,
    max_points: int = 50000,
) -> Path:
    try:
        import torch
        from vggt.models.vggt import VGGT
        from vggt.utils.geometry import unproject_depth_map_to_point_map
        from vggt.utils.load_fn import load_and_preprocess_images
        from vggt.utils.pose_enc import pose_encoding_to_extri_intri
    except ModuleNotFoundError as exc:
        if exc.name and exc.name.startswith("vggt"):
            raise RuntimeError(
                "optional VGGT dependency is not installed; run this command in a "
                "cloud/GPU environment with facebookresearch/vggt installed"
            ) from exc
        raise

    manifest = read_frame_manifest(frame_manifest_path)
    image_names = [str(frame.path) for frame in manifest.frames]
    device = "cuda" if torch.cuda.is_available() else "cpu"
    if device == "cpu" and not allow_cpu:
        raise RuntimeError(
            "CUDA is not available; refusing CPU VGGT inference by default on this "
            "large model. Re-run with --allow-cpu only if the machine can handle it."
        )
    dtype = torch.bfloat16 if device == "cuda" and torch.cuda.get_device_capability()[0] >= 8 else torch.float16

    model = VGGT.from_pretrained("facebook/VGGT-1B").to(device)
    model.eval()
    images = load_and_preprocess_images(image_names).to(device)
    with torch.no_grad():
        autocast_device = "cuda" if device == "cuda" else "cpu"
        with torch.amp.autocast(autocast_device, dtype=dtype, enabled=device == "cuda"):
            predictions = model(images)
            extrinsic, intrinsic = pose_encoding_to_extri_intri(
                predictions["pose_enc"], images.shape[-2:]
            )
            predictions["extrinsic"] = extrinsic
            predictions["intrinsic"] = intrinsic
            if "depth" in predictions:
                world_points = unproject_depth_map_to_point_map(
                    _to_numpy_array(predictions["depth"].squeeze(0)),
                    _to_numpy_array(extrinsic.squeeze(0)),
                    _to_numpy_array(intrinsic.squeeze(0)),
                )
                predictions["world_points_from_depth"] = world_points

    numpy_predictions = {}
    for key, value in predictions.items():
        try:
            value = _to_numpy_array(value)
            value = np.asarray(value)
        except Exception as exc:
            raise RuntimeError(f"could not convert prediction {key!r} to numpy: {exc}") from exc
        if value.dtype == object:
            continue
        if value.shape[:1] == (1,):
            value = value.squeeze(0)
        numpy_predictions[key] = value

    predictions_output = predictions_output.resolve()
    predictions_output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(predictions_output, **numpy_predictions)
    return import_predictions_npz(
        predictions_path=predictions_output,
        frame_manifest_path=frame_manifest_path,
        output=bundle_output,
        source_tool="local-vggt",
        source_url_or_repo=source_url_or_repo,
        source_commit_or_version=source_commit_or_version,
        export_notes="Generated by optional fpv vggt run-installed command.",
        max_points=max_points,
    )
